# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	rk3568-psv-plc-050.dtbo \
	rk3568-psv-plc-070.dtbo \
	rk3568-psv-plc-101.dtbo \
	rk3568-psv-plc-104.dtbo \
	rk3568-psv-plc-121.dtbo \
	rk3568-psv-plc-150.dtbo \
	rk3568-psv-plc-170.dtbo \
	rk3568-psv-plc-190.dtbo \
	rk3568-psv-plc-215.dtbo \
	rk3568-psv-plc-240.dtbo \
	rk3568-psv-plc-no-front-sd.dtbo \
	rk3568-psv-plc-no-front-usb.dtbo \
	rk3568-psv-plc-din.dtbo \

targets += $(dtbo-y)

always-y		:= $(dtbo-y)
clean-files		:= *.dtbo
